import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // This function could be used to send a desktop notification
  async function sendNotification() {
    // Check if the browser supports notifications
    if (!('Notification' in window)) {
      alert('This browser does not support desktop notification');
      return;
    }

    // Check whether notification permissions have already been granted
    if (Notification.permission === 'granted') {
      // If it's okay, create a notification
      console.log('notification triggered');
      const notification = new Notification('Notification Title', {
        body: 'Push notification',
        icon: '/icons/icon-192x192.png',
      });

      // Handle click events on the notification
      notification.onclick = function () {
        console.log('Notification clicked');
      };
    } else if (Notification.permission !== 'denied' || Notification.permission === 'default') {
      // Otherwise, ask the user for permission
      const permission = await Notification.requestPermission();
      // If the user accepts, let's create a notification
      if (permission === 'granted') {
        const notification = new Notification('Notification Title', {
          body: 'Here is the message body',
          icon: '/icons/icon-192x192.png',
        });

        // Handle click events on the notification
        notification.onclick = function () {
          console.log('Notification clicked');
        };
      }
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={72}
                height={16}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            src="/next.svg"
            alt="Next.js Logo"
            className={styles.logo}
            width={180}
            height={37}
            priority
          />
        </div>

        <button onClick={sendNotification} className={styles.card}>
            Send Push Notification
          </button>
          
        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
